### PR TITLE
Use parseArgs to handle script args

### PR DESCRIPTION
**Pull request by josephmturner**

### CODE REVIEW

**Comment by josephmturner** [comment]
Actually, we might not want to use parseArgs, since it requires Node version 16 or 18.

**Comment by josephmturner** [comment]
On second thought, we could use this [polyfill](https://www.npmjs.com/package/@pkgjs/parseargs). What's the correct way to pull in the polyfill as necessary?

**Comment by RangerMauve** [comment]
I would rather not use a polyfill or any extra dependencies for this. Is using node 18 out of the question for your use case?

**Comment by josephmturner** [comment]
The reason I wanted to use Node 14 is that it's the latest version supported by Guix. Not a big deal.

**Pull request closed without merging**
